### ISSUE TITLE
Incompatible proxied ApiGatewayEvent

### ISSUE THREAD

**Issue by S-Cardenas** [elthrasher/http-lambda-invoker#19]
First of all I'd like to say "GREAT WORK!" on this project. The implementation so far is great and the general idea i believe is in the right direction. @elthrasher 

One of the major issues I see with it right is that the "Lamda-Proxy Event" that is being sent from `elthrasher/http-lambda-invoker` to the lambda container is not truly representative of the event that API Gateway sends to a lambda function. Currently you are sending the proxy event in this format:

```
{
  "body": "",
  "headers": {
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
    ],
    "Accept-Encoding": [
      "gzip, deflate, br"
    ],
    "Accept-Language": [
      "en-US,en;q=0.9"
    ],
    "Cache-Control": [
      "no-cache"
    ],
    "Connection": [
      "keep-alive"
    ],
    "Pragma": [
      "no-cache"
    ],
    "Sec-Fetch-Dest": [
      "document"
    ],
    "Sec-Fetch-Mode": [
      "navigate"
    ],
    "Sec-Fetch-Site": [
      "none"
    ],
    "Sec-Fetch-User": [
      "?1"
    ],
    "Upgrade-Insecure-Requests": [
      "1"
    ],
    "User-Agent": [
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"
    ]
  },
  "httpMethod": "GET",
  "path": "/graphql",
  "queryStringParameters": {}
}
```

In reality API Gateway sends the event with much more information that is essential to executing the lambda function such as:

```
{
  "body": null,
  "headers": {
    "Host": "localhost:8080",
    "Connection": "keep-alive",
    "Pragma": "no-cache",
    "Cache-Control": "no-cache",
    "Upgrade-Insecure-Requests": "1",
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36",
    "Sec-Fetch-Dest": "document",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "Sec-Fetch-Site": "none",
    "Sec-Fetch-Mode": "navigate",
    "Sec-Fetch-User": "?1",
    "Accept-Encoding": "gzip, deflate, br",
    "Accept-Language": "en-US,en;q=0.9",
    "X-Forwarded-Proto": "http",
    "X-Forwarded-Port": "8080"
  },
  "httpMethod": "GET",
  "isBase64Encoded": false,
  "multiValueHeaders": {
    "Host": [
      "localhost:8080"
    ],
    "Connection": [
      "keep-alive"
    ],
    "Pragma": [
      "no-cache"
    ],
    "Cache-Control": [
      "no-cache"
    ],
    "Upgrade-Insecure-Requests": [
      "1"
    ],
    "User-Agent": [
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
    ],
    "Sec-Fetch-Dest": [
      "document"
    ],
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
    ],
    "Sec-Fetch-Site": [
      "none"
    ],
    "Sec-Fetch-Mode": [
      "navigate"
    ],
    "Sec-Fetch-User": [
      "?1"
    ],
    "Accept-Encoding": [
      "gzip, deflate, br"
    ],
    "Accept-Language": [
      "en-US,en;q=0.9"
    ],
    "X-Forwarded-Proto": [
      "http"
    ],
    "X-Forwarded-Port": [
      "8080"
    ]
  },
  "multiValueQueryStringParameters": null,
  "path": "/graphql",
  "pathParameters": null,
  "queryStringParameters": null,
  "requestContext": {
    "resourceId": "123456",
    "apiId": "1234567890",
    "resourcePath": "/graphql",
    "httpMethod": "GET",
    "requestId": "c6af9ac6-7b61-11e6-9a41-93e8deadbeef",
    "accountId": "123456789012",
    "stage": "dev",
    "identity": {
      "apiKey": null,
      "userArn": null,
      "cognitoAuthenticationType": null,
      "caller": null,
      "userAgent": "Custom User Agent String",
      "user": null,
      "cognitoIdentityPoolId": null,
      "cognitoAuthenticationProvider": null,
      "sourceIp": "127.0.0.1",
      "accountId": null
    },
    "extendedRequestId": null,
    "path": "/graphql"
  },
  "resource": "/graphql",
  "stageVariables": null
}
```

Would it be possible to update the api proxy so that sends over an event similar to the one seen in an actual Actual Api Gateway or at least similar to that used by SAM Local?

**Comment by elthrasher** [comment]
Yeah absolutely, I'll look at building out that functionality in the coming weeks. Happy to consider a PR if you can't wait or want to contribute.

**Comment by S-Cardenas** [comment]
@elthrasher I made some small changes to how the proxied request headers are built and would like to open up a PR. I think I need access to be able to create the PR.

Let me know.

**Comment by elthrasher** [comment]
You should be able to fork the project and submit a PR that way.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Can you describe your use case? I have a mind to go after httpapi and/or parse SAM templates, but if you're looking for something else, let's get to it! 🚀

**Comment by S-Cardenas** [comment]
Currently I'm using a lambda function to host a GraphQL endpoint. The lambda function uses layers which was causing AWS SAM Api Gateway to rebuild the layer image on each request. Regardless of the layer, the requests were extremely slow for local development.

I think we should start by parsing SAM templates since that would make it very easy to integrate into existing serverless workflows. Let me know how I can help. As you'll see by my [PR ](https://github.com/elthrasher/http-lambda-invoker/pull/21)I have no experience in Golang, this PR was literally my first usage of it, but I'll contribute in whatever way I can.

**Comment by elthrasher** [comment]
Cool thanks. I created an issue for SAM: https://github.com/elthrasher/http-lambda-invoker/issues/23. Feel free to drop any thoughts you have there.

**Comment by elthrasher** [comment]
Fixed in https://github.com/elthrasher/http-lambda-invoker/pull/21
