### ISSUE TITLE
Request body is getting base64 encoded

### ISSUE THREAD

**Issue by mcintyre94** [elthrasher/http-lambda-invoker#58]
I think this is because of the type:

```go
type makeProxyRequest struct {
	Body              []byte              `json:"body"`
	Headers           proxyHeader         `json:"headers"`
	HTTPMethod        string              `json:"httpMethod"`
	Path              string              `json:"path"`
	QueryStringParams map[string][]string `json:"queryStringParameters"`
}
```

When JSON marshal is used on that type, it base64 encodes the `[]byte` per https://golang.org/pkg/encoding/json/#Marshal

> Array and slice values encode as JSON arrays, except that []byte encodes as a base64-encoded string, and a nil slice encodes as the null JSON value. 

But this doesn't seem desirable for this use case? The lambda using API Gateway doesn't usually receive a base 64 encoded body, so it's not getting the expected input here. Do you have a workaround for this issue at all?

**Comment by S-Cardenas** [comment]
@mcintyre94 I ran into the same issue and implemented something like this in the lambda handler:

```
  if (process.env.IN_DOCKER_LAMBDA === 'true') {
    if (event.body) {
      // As of now the, 'elthrasher/http-lambda-invoker' is marshalling the request
      // and returning a base64 encoded body.
      let buff = new Buffer(event.body, 'base64');
      let body = buff.toString('ascii');
      event.body = body;
    }

    lambdaEvent = event;
   } else {
    lambdaEvent = event;
   }
```

I would love for their to be an actual solution built into library however. This is very much a "patch".

**Comment by elthrasher** [comment]
@mcintyre94 So sorry for not getting back to you. TIL after a decade with github that I don't automatically get notifications on issues. :(

I'll see if I can use a different type there. I agree that seems weird.

**Comment by elthrasher** [comment]
Okay, this was pretty simple to fix and you can chalk it up to my inexperience with golang.

@S-Cardenas and @mcintyre94 are you using the above hack right now? If I just release the fix, I assume that would break some process you have. I guess I should add image tagging instead of stamping everything with `latest`.

**Comment by mcintyre94** [comment]
Awesome, thanks for taking a look at this @elthrasher :) I’m using the above hack yep, would be great to get rid of it though!

I’m fine to move from latest to a versioned image once you have that fix. I think it’s fine to have backward incompatibilities on latest, but would be easiest if you could push the current version with a versioned tag first so I can switch to that and then make the changes. 

Thanks again for fixing this though, it’ll make a big difference :)

**Comment by elthrasher** [comment]
Okay, I've tagged the current head: `docker pull elthrasher/http-lambda-invoker:release-0.0.1`

I'll release the fix today or tomorrow. Just want to figure out if I can have better unit tests (still learning go).

**Comment by elthrasher** [comment]
Since it's technically a breaking change, I posted the fix to `docker pull elthrasher/http-lambda-invoker:release-0.1.0` and it's in `latest` as well. Please let me know if that works.

**Comment by mcintyre94** [comment]
Awesome, I'll try the fix out at work tomorrow - thanks again! :)

**Comment by mcintyre94** [comment]
@elthrasher Tested this now and 0.1.0 is working great - perfect! I'll close this issue now :)

**Comment by S-Cardenas** [comment]
I'll test the fix out later today. Regardless thanks for implementing it and keeping this project alive. Kudos 👍

**Comment by elthrasher** [comment]
Thanks guys. I appreciate the feedback. My team isn't actually using this yet, so you guys are saving us some future churn. 👍
